apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: my-apps
  name: productpage-virtual-router
spec:
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  routes:
    - name: productpage-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: productpage-v1
              weight: 1
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: my-apps
  name: reviews-virtual-router
spec:
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  routes:
    - name: reviews-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef: 
                name: reviews-v1
              weight: 1
            - virtualNodeRef: 
                name: reviews-v2
              weight: 2
            - virtualNodeRef: 
                name: reviews-v3
              weight: 1
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: my-apps
  name: ratings-virtual-router
spec:
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  routes:
    - name: ratings-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: ratings-v1
              weight: 1
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: my-apps
  name: details-virtual-router
spec:
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  routes:
    - name: details-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: details-v1
              weight: 1
---