apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: details-v1
  namespace: my-apps
spec:
  podSelector:
    matchLabels:
      app: details
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: details-v1.my-apps.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: productpage-v1
  namespace: my-apps
spec:
  podSelector:
    matchLabels:
      app: productpage
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  backends:
    - virtualService:
        virtualServiceRef:
          name: details
    - virtualService:
        virtualServiceRef:
          name: reviews
  serviceDiscovery:
    dns:
      hostname: productpage-v1.my-apps.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: ratings-v1
  namespace: my-apps
spec:
  podSelector:
    matchLabels:
      app: ratings
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: ratings-v1.my-apps.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: reviews-v1
  namespace: my-apps
spec:
  podSelector:
    matchLabels:
      app: reviews
      version: v1
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  backends:
  - virtualService:
      virtualServiceRef:
        name: ratings
  serviceDiscovery:
    dns:
      hostname: reviews-v1.my-apps.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: reviews-v2
  namespace: my-apps
spec:
  podSelector:
    matchLabels:
      app: reviews
      version: v2
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  backends:
  - virtualService:
      virtualServiceRef:
        name: ratings
  serviceDiscovery:
    dns:
      hostname: reviews-v2.my-apps.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: reviews-v3
  namespace: my-apps
spec:
  podSelector:
    matchLabels:
      app: reviews
      version: v3
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  backends:
  - virtualService:
      virtualServiceRef:
        name: ratings
  serviceDiscovery:
    dns:
      hostname: reviews-v3.my-apps.svc.cluster.local